
import './globals.css'
import * as React from 'react'
import { Inter } from 'next/font/google'
import Providers from './Providers'
import Themechanger from './components/ThemeSwitcher'




const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'JS Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className='overflow-x-hidden'>
            <Themechanger />
            {children}
          </div>
        </Providers>
      </body>
    </html>

  )
}
